jobs:
  darkube_build_zanjir-chain_nobitex_hamravesh-c13:
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME: h-reg.nxbo.ir/labs/zanjir-chain
    runs-on: ubuntu-latest
    steps:
    - name: checkout commit
      uses: actions/checkout@v4
    - name: darkube-cli build & push
      run: |
        darkube build --push \
          -t $IMAGE_NAME:${GITHUB_SHA:0:7} \
          -t $IMAGE_NAME:${GITHUB_REF_NAME} \
          --docker-auth-config ${{ secrets.DOCKER_AUTH_CONFIG }} \
          --workdir . \
          --file ./Dockerfile \
          --build-context .
'on':
  push:
    branches:
    - main
